name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

        # Check out the repository
      - name: Checking out repository
        uses: actions/checkout@v4

        # Setup Node.js
      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

        # Install NPM dependencies
      - name: NPM install
        run: npm ci

        # Build
      - name: Build
        run: npm run build

        # Configure AWS Credentials
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

        # Copy files to S3
      - name: Copy files to S3
        run: aws s3 sync --delete ./dist/ s3://app.freepethealth.com

        # Invalidate cached files
      - name: Invalidate cached files
        run: aws cloudfront create-invalidation --distribution-id XXXXXXXXXXXX --paths "/*"
